### ISSUE TITLE
Mystral#newAsyncDatabase() should also throw SQLException

### ISSUE THREAD

**Issue by nicecraftz** [Glyart/Mystral#4]
It should throw it just so you can handle it <3

**Comment by Valxrie** [comment]
No, it shouldn't. As stated in the [Javadocs](https://docs.oracle.com/javase/7/docs/api/java/sql/SQLException.html), SQLException "provides information on a **database access error** or other errors".

Mystral#newAsyncDatabase() supplies a new AsyncDatabase object, which contains a DataSource implementation. By default, that implementation is [HikariDataSource](https://www.javadoc.io/doc/com.zaxxer/HikariCP/3.2.0/com/zaxxer/hikari/HikariDataSource.html).  
A DataSource instantiation doesn't need to throw a SQLException. Also, HikariDataSource uses a connection-pooling system, and it throws an exception on its own, which is wrapped inside Mystral's DataSourceInitException, for better usage.  

SQLException is legally threw when you are trying to access the database via [DataSource#getConnection](https://docs.oracle.com/javase/7/docs/api/javax/sql/DataSource.html#getConnection()) (which is what Mystral does internally). This happens because you inserted the wrong credentials data.  
Please, be sure they are correct before performing any dbms-related operation.
